/**
 * src/lib/observation-deletion.test.ts
 * =====================================
 * Tests for Observation Deletion by verified government officials,
 * dispatchers, and administrators, and Security Alert generation restrictions.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";

// ── Env setup ─────────────────────────────────────────────────────────────
process.env["SUPABASE_URL"] = "https://shkpwbqcbeqlybdrhczq.supabase.co";
process.env["SUPABASE_SERVICE_ROLE_KEY"] = "sb_secret_test_key_for_testing";

// ── In-memory observation store ───────────────────────────────────────────
const MOCK_OBSERVATIONS: Record<string, any> = {
  "101": {
    id: 101,
    zone_id: 1,
    status: "PENDING_VERIFICATION",
    visual_signs: "Minor slope slumping",
    observed_at: new Date().toISOString(),
  },
  "102": {
    id: 102,
    zone_id: 2,
    status: "VERIFIED",
    visual_signs: "Tension crack across roadway",
    observed_at: new Date().toISOString(),
  },
};

// ── Supabase admin mock ───────────────────────────────────────────────────
vi.mock("@/integrations/supabase/client.server", () => {
  const makeQuery = (table: string) => {
    const state: { filters: Record<string, unknown> } = {
      filters: {},
    };

    const query: any = {
      select: (_cols: string) => query,
      eq: (col: string, val: unknown) => {
        state.filters[col] = val;
        return query;
      },
      maybeSingle: async () => {
        if (table === "field_observations") {
          const id = String(state.filters["id"] ?? "");
          const row = MOCK_OBSERVATIONS[id] ?? null;
          return { data: row, error: null };
        }
        return { data: null, error: null };
      },
      delete: () => ({
        eq: async (col: string, val: unknown) => {
          state.filters[col] = val;
          const id = String(val);
          delete MOCK_OBSERVATIONS[id];
          return { data: null, error: null };
        },
      }),
      insert: async (data: unknown) => ({ data, error: null }),
    };

    return query;
  };

  return {
    supabaseAdmin: {
      from: (table: string) => makeQuery(table),
      auth: {
        getUser: async () => ({ data: { user: null }, error: { message: "not used" } }),
      },
      rpc: async () => ({ data: null, error: null }),
    },
  };
});

import {
  deleteGroundObservation,
  verifyDispatcherAuthorization,
  type UserProfileRecord,
} from "./official-auth.service";
import { handleApiRequest } from "./api.router";

describe("Security Alerts & Observation Deletion Official Authorization", () => {
  const officialUser: UserProfileRecord = {
    id: "test-official-uuid",
    email: "officer@gsi.gov.in",
    role: "VERIFIED_OFFICIAL",
    verification_status: "VERIFIED",
    dispatch_authorized: false,
    institution: "Geological Survey of India",
  };

  const dispatcherUser: UserProfileRecord = {
    id: "test-dispatcher-uuid",
    email: "dispatcher@ddma.gov.in",
    role: "DISPATCHER",
    verification_status: "VERIFIED",
    dispatch_authorized: true,
    institution: "District Disaster Management Authority",
  };

  const adminUser: UserProfileRecord = {
    id: "test-admin-uuid",
    email: "admin@ndma.gov.in",
    role: "ADMIN",
    verification_status: "VERIFIED",
    dispatch_authorized: true,
    institution: "National Disaster Management Authority",
  };

  const publicUser: UserProfileRecord = {
    id: "test-anon-citizen-uuid",
    email: "citizen@example.com",
    role: "PUBLIC_USER",
    verification_status: "UNVERIFIED",
    dispatch_authorized: false,
  };

  beforeEach(() => {
    MOCK_OBSERVATIONS["101"] = {
      id: 101,
      zone_id: 1,
      status: "PENDING_VERIFICATION",
      visual_signs: "Minor slope slumping",
      observed_at: new Date().toISOString(),
    };
    MOCK_OBSERVATIONS["102"] = {
      id: 102,
      zone_id: 2,
      status: "VERIFIED",
      visual_signs: "Tension crack across roadway",
      observed_at: new Date().toISOString(),
    };
  });

  describe("Security Alert Generation Authorization", () => {
    it("prohibits unauthenticated and public users from generating security alerts", async () => {
      const unauthResult = await verifyDispatcherAuthorization(
        {
          userId: "unauthenticated_caller",
          role: "PUBLIC_USER",
          dispatchAuthorized: false,
        },
        1,
        "Field inspection confirms rockfall",
      );
      expect(unauthResult.authorized).toBe(false);
      expect(unauthResult.reason).toContain("Security alerts can only be generated by authorized security officials");

      const publicResult = await verifyDispatcherAuthorization(
        {
          userId: "public-123",
          email: "citizen@gmail.com",
          role: "PUBLIC_USER",
          dispatchAuthorized: false,
        },
        1,
        "Slope crack visible from road",
      );
      expect(publicResult.authorized).toBe(false);
      expect(publicResult.reason).toContain("Security alerts can only be generated by authorized security officials");
    });

    it("prohibits verified officials without dispatch authorization from generating security alerts", async () => {
      const officialResult = await verifyDispatcherAuthorization(
        {
          userId: officialUser.id,
          email: officialUser.email,
          role: officialUser.role,
          dispatchAuthorized: false,
        },
        1,
        "Geologist observing slope movement",
      );
      expect(officialResult.authorized).toBe(false);
      expect(officialResult.reason).toContain("Security alerts can only be generated by authorized security officials");
    });

    it("allows authorized dispatchers and admins to generate security alerts", async () => {
      const dispatcherResult = await verifyDispatcherAuthorization(
        {
          userId: dispatcherUser.id,
          email: dispatcherUser.email,
          role: dispatcherUser.role,
          dispatchAuthorized: true,
        },
        1,
        "Heavy debris flow observed blocking highway NH-29",
      );
      expect(dispatcherResult.authorized).toBe(true);

      const adminResult = await verifyDispatcherAuthorization(
        {
          userId: adminUser.id,
          email: adminUser.email,
          role: adminUser.role,
          dispatchAuthorized: true,
        },
        1,
        "Critical threshold breach triggering emergency evacuation order",
      );
      expect(adminResult.authorized).toBe(true);
    });
  });

  describe("Observation Individual Deletion Authorization", () => {
    it("rejects observation deletion by public / non-official users", async () => {
      const result = await deleteGroundObservation(
        publicUser,
        "101",
        "Citizen trying to delete record",
      );
      expect(result.success).toBe(false);
      expect(result.error).toContain("Forbidden: Only verified government officials");
      expect(MOCK_OBSERVATIONS["101"]).toBeDefined();
    });

    it("allows verified officials to delete individual observations", async () => {
      const officialResult = await deleteGroundObservation(
        officialUser,
        "101",
        "Duplicate report removed by official",
      );
      expect(officialResult.success).toBe(true);
      expect(MOCK_OBSERVATIONS["101"]).toBeUndefined();
    });

    it("allows dispatchers and admins to delete individual observations", async () => {
      const dispatcherResult = await deleteGroundObservation(
        dispatcherUser,
        "102",
        "Invalid observation removed by dispatcher",
      );
      expect(dispatcherResult.success).toBe(true);
      expect(MOCK_OBSERVATIONS["102"]).toBeUndefined();
    });

    it("returns 404 error when attempting to delete a non-existent observation", async () => {
      const result = await deleteGroundObservation(
        officialUser,
        "99999",
        "Removing ghost observation",
      );
      expect(result.success).toBe(false);
      expect(result.error).toContain("Observation 99999 not found");
    });

    it("enforces authentication on /api/observations/delete REST endpoint", async () => {
      const unauthReq = new Request("http://localhost:3000/api/observations/delete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ observation_id: "101" }),
      });
      const unauthRes = await handleApiRequest(unauthReq);
      expect(unauthRes?.status).toBe(401);

      const publicReq = new Request("http://localhost:3000/api/observations/delete", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: "Bearer test-authenticated-public",
        },
        body: JSON.stringify({ observation_id: "101" }),
      });
      const publicRes = await handleApiRequest(publicReq);
      expect(publicRes?.status).toBe(403);
    });

    it("enforces authentication on DELETE /api/observations/:id REST endpoint", async () => {
      const deleteReq = new Request("http://localhost:3000/api/observations/101", {
        method: "DELETE",
        headers: {
          Authorization: "Bearer test-authenticated-public",
        },
      });
      const deleteRes = await handleApiRequest(deleteReq);
      expect(deleteRes?.status).toBe(403);
    });

    it("successfully deletes observation via POST /api/observations/delete when called by official", async () => {
      const req = new Request("http://localhost:3000/api/observations/delete", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: "Bearer test-authenticated-official",
        },
        body: JSON.stringify({ observation_id: "101", reason: "Spam entry purged" }),
      });
      const res = await handleApiRequest(req);
      expect(res?.status).toBe(200);
      const json = await res?.json();
      expect(json.ok).toBe(true);
      expect(json.observation_id).toBe("101");
      expect(MOCK_OBSERVATIONS["101"]).toBeUndefined();
    });

    it("successfully deletes observation via DELETE /api/observations/:id when called by official", async () => {
      const req = new Request("http://localhost:3000/api/observations/102", {
        method: "DELETE",
        headers: {
          Authorization: "Bearer test-authenticated-official",
        },
      });
      const res = await handleApiRequest(req);
      expect(res?.status).toBe(200);
      const json = await res?.json();
      expect(json.ok).toBe(true);
      expect(json.observation_id).toBe("102");
      expect(MOCK_OBSERVATIONS["102"]).toBeUndefined();
    });

    it("validates missing observation_id parameter", async () => {
      const emptyReq = new Request("http://localhost:3000/api/observations/delete", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: "Bearer test-authenticated-official",
        },
        body: JSON.stringify({}),
      });
      const emptyRes = await handleApiRequest(emptyReq);
      expect(emptyRes?.status).toBe(400);
      const json = await emptyRes?.json();
      expect(json.code).toBe("MISSING_OBSERVATION_ID");
    });
  });
});
